### ISSUE TITLE
function names container keywords are colored incorrectly

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#12]
Functions that start with `delete` or `namespace` are not colored as functions, and the keyword portion is colored as a keyword.

Additionally, functions whose names are identifiers with special meaning are again not colored as functions.

See photo.
![screenshot from 2019-03-07 10-02-55](https://user-images.githubusercontent.com/714007/53978966-5c205780-40c1-11e9-93da-3bb5223070fb.png)

This issue is not present in the default c/cpp grammar
![screenshot from 2019-03-07 10-02-32](https://user-images.githubusercontent.com/714007/53979053-91c54080-40c1-11e9-8b54-465e76f92dcf.png)

Thanks

**Comment by jeff-hykin** [comment]
Thanks for pointing this out, I'll look into it and should have a fix before Monday and hopefully sooner

**Comment by jeff-hykin** [comment]
Alright everything should be fixed in version 1.4.9 (pushed just now).

**Comment by matter123** [comment]
Thank you for the quick update but the issue still exists for several identifiers with special meaning

![screenshot from 2019-03-07 10-34-06](https://user-images.githubusercontent.com/714007/53980291-d3a3b600-40c4-11e9-92cc-1fec51400b2f.png)

Thanks

**Comment by jeff-hykin** [comment]
Dang sorry I missed that, I promise I wasn't just adding edge cases haha. It should be fixed now with version 1.4.10 (including for names that are not in the screenshot like `co_await`, `co_yield`, `export`, `import`, etc) To be honest I'm really surprised C++ allows `override` and `final`.

Change Summary:
- to `new`, `delete`, `delete[]`
- to `namespace` definition
- to valid-function-name list (which many patterns use)

Let me know if there are any other groups I'm missing. I will try to look at the actual C++ specifications this weekend to make sure the token list matches it.

**Comment by matter123** [comment]
Sorry, but you went a bit overboard.

[C++20 draft](http://eel.is/c++draft) [lex.key]/table 5 says `concept`, and `requires` are reserved keywords.

[n4514](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4514.pdf) only adds `transaction_safe` and `transaction_safe_dynamic` to the list of identifiers with special meaning. `synchronized`, `atomic_noexcept`, `atomic_cancel`, and `atomic_commit` are all reserved keywords.

[n4775](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4775.pdf) adds `co_await`, `co_yield`, and `co_return` to the table of reserved keywords.

[n4720](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4720.pdf) adds `module` and `import` to the table of reserved keywords.

[n4766](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4766.pdf) adds `reflexpr` to the table of reserved keywords.

Thanks

**Comment by jeff-hykin** [comment]
Wow, you really know your C++ specs. Thanks for following up with that in such great detail.  I re-marked those as invalid function names and pushed an update for it. Hopefully thats the last change for this issue 😅
