### ISSUE TITLE
using namespace has the wrong scope?

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/cpp-textmate-grammar#259]
Is this a bug? I'm seeing using namespace have some "parameter" TM scope instead of the previous scopes.

![image](https://user-images.githubusercontent.com/19859882/60142906-c5ab9b00-9770-11e9-8dc3-7581bde2c355.png)

**Comment by jeff-hykin** [comment]
that shouldn't be the case (some kind of bug), what is the full code snippet?

**Comment by sean-mcmanus** [comment]
Oh strange -- the code appeared to be just the 1st line in a method, so I assumed the repro was easy, but I just tried a simple project and it's not reproing, so it looks like something early on our code is causing some failure. I'll see if I can get an isolated repro....

**Comment by sean-mcmanus** [comment]
Here's a repro below -- the lambda is causing breakage on all "using namespace" that occurs later on in the file -- using some incorrect parameter TM scopes:
```
#include <vector>
#include <string>
#include <memory>

class cc;
int func()
{
  auto a = [](std::vector<std::shared_ptr<cc>> c)
    {
    };
  using namespace std::literals;
}
```

**Comment by jeff-hykin** [comment]
Ah it was the `std::vector<std::shared_ptr<cc>>` that was causing the issue. Thankfully this is already fixed in `v1.12.3`. Thanks for reporting this though.

**Comment by matter123** [comment]
I can still reproduce this is 1.12.3.
![Screenshot from 2019-06-26 17-49-01](https://user-images.githubusercontent.com/714007/60225222-babd3d00-983a-11e9-8c29-afcd25b32477.png)

**Comment by jeff-hykin** [comment]
Ah you're right good catch, the changes were made but not published yet. They're published now under `v1.12.4`
