### ISSUE TITLE
Highlighting error when defining global variables with construction functions

### ISSUE THREAD

**Issue by Dust1404** [jeff-hykin/cpp-textmate-grammar#282]
VSCode 1.35.1
Better C++ Syntax 1.12.11

similar to #206 

![1](https://user-images.githubusercontent.com/40361332/60556516-53d8e000-9d74-11e9-9532-04077770b668.PNG)
![2](https://user-images.githubusercontent.com/40361332/60556517-56d3d080-9d74-11e9-9831-2cf59f1bc83c.PNG)

```cpp
#include <ctime>
#include <cstdio>
#include <random>

std::mt19937 eng1(std::time(nullptr));
// std::mt19937 eng2(1234);
// int n(1234);
// 3 lines above can all cause the problem

int main()
{
	printf("Hello World!\n");

	return 0;
}
```

**Comment by matter123** [comment]
So to summarize this issue:
 - function calls inside of potential function definitions cause the paramater**s** to not end at the second `)`
 - literals are not highlighted and cause the same issue.

**Comment by matter123** [comment]
@jeff-hykin When there is a ambiguity between a function definition and a constructor call should the highlighting of A foo(A,B,C) as `entity.name.type.parameter` be disabled?

**Comment by matter123** [comment]
@jeff-hykin It would be possible to first try matching a single line to look for a valid function definition and fall back on the pattern-range only if the definition spread across more than one line? That should make it possible to detect that `void *foo(nullptr);` is not a function definition.

**Comment by jeff-hykin** [comment]
This is a serious problem, and might undo all of my work with parameters.

You probably already know this stuff @matter123 , I'm going to summarize it for myself and others though. 

### Multi-line fix  (a complete fix)
Fundamentally This issue is that there's no pattern for function initializations.  
```
aType aThing(     // this is a function
    int a
);
```
```
aType aThing(    // this is an initialization 
    "testing"
);
```
Textmate can only look at one line before irreversibly jumping into a range. Right now when it sees `aType aThing(` irreversibly jumps into the function-definition range. There is no way for the grammar to know if its a function or a multi-line initialization until after the first line, this is fundamentally not possible in the textmate grammar. (However, the tree-sitter parser could handle this).

### All one line cases
`int thing1(thing2);` // a prototype function if thing2 is a type
`int thing1(thing2);` // an initialization if thing2 is a variable
Textmate (and also the tree-sitter-parser) has no way of knowing if `thing2` is a type or a variable.
This is unsolvable without a language specific parser/server.

### Special cases of one liners
`int *aVar(nullptr);`
`string aVar("test");`
`string aVar( aType{"test"} );`
`SomeType aVar(variable1, variable2, "test");`
`SomeType aVar(variable1, variable2, "test",  aType{  aType{"test"}, "test"} );`
This, as @matter123 mention is possible to detect. There only needs to be one literal value or one initialization that contains a literal value. However, while the first case is trivial, the cases become increasingly non-trival to the point of extreme complexity by the 5th example.

## The makeshift solution (then old and probably future answer)
Rather than knowing if it actually is a function call or an initialization, its possible to pretend that it is always both, and then highlight things accordingly. The reason this isn't working right now is because, in order to make the parameters be highlighted better, some assumptions were made that are perfectly valid for function definitions. However, those assumptions are screwing up inside of initializations.

I'm going to try to make a partial fix to make this problem not cascade beyond the initialization parentheses. I'll close this issue once that is fixed. However, I'll create another issue for the more general problem, including deciding how to tag the ambiguous `A foo(A,B,C)`.

**Comment by jeff-hykin** [comment]
Fixed an pushed with `v1.12.13`

**Comment by Dust1404** [comment]
The problem still exists in `v1.12.14`.

![1](https://user-images.githubusercontent.com/40361332/60637318-94a42800-9e4c-11e9-9159-328aaaad4c7b.PNG)
![2](https://user-images.githubusercontent.com/40361332/60637320-95d55500-9e4c-11e9-8e2f-403fe32ae1f0.PNG)
![3](https://user-images.githubusercontent.com/40361332/60637321-979f1880-9e4c-11e9-9947-2d3307ad531b.PNG)

```cpp
mt19937 gen(time(nullptr) ^ (size_t) new char);
// mt19937 gen(1234);
// mt19937 gen(time(nullptr));

inline int randint(int l, int r)
{
	return uniform_int_distribution<>(l, r)(gen);
}

int main()
{
	for (int i = 1; i <= N; ++i)
		R[i] = randint(0, 100) & 31;

	return 0;
}
```

**Comment by matter123** [comment]
The main issue has been fixed in v1.12.15. There is an issue with the highlighting of size_t, Ill file a separate issue.

**Comment by jeff-hykin** [comment]
@Dust1404  let me know if you find any more cases. I'm pretty confident this most recent change will have covered all of them.
